apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: service-name
  app.kubernetes.io/name: service-name
  app.kubernetes.io/instance: service-name

resources:
  - deployment.yaml
  - svc.yaml
  - ingress.yaml
