{{- if .Values.serviceConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}
data:
  {{- range $k, $v := .Values.serviceConfig }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
