apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        app.kubernetes.io/version: {{ .Values.image.tag }}
        app.kubernetes.io/name: {{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          envFrom:
          {{- if .Values.serviceConfig }}
          - configMapRef:
              name: {{ .Values.serviceName }}
          {{- end }}
          {{- if .Values.configMapRef }}
          - configMapRef:
                name: {{ .Values.configMapRef }}
          {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range $secret := .Values.image.pullSecrets }}
        - name: {{ $secret | quote }}
        {{- end }}
      {{- end }}
