apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: 80
      {{- if .Values.host }}
      host: {{ .Values.host }}
      {{- end }}
