apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
spec:
  selector:
    app: {{.Values.serviceName}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.containerPort}}
